language: node_js
node_js:
- "4.5.0"
before_install:
  - npm config set registry http://registry.npmjs.org/
install:
- npm install
before_script:
  - npm install -g gulp
script: gulp dragoman
notifications:
  slack: dragoman-devops:ohWKCvgdvuAArargPHjr48CA