title: Dragoman
description: Github page for Dragoman tool

url: "https://NateBaldwinDesign.github.io/"
baseurl: "/dragoman"
paginate_path: "blog/page:num/"
permalink: blog/:title/

exclude: ["node_modules", "config.rb", "Gemfile", "Gemfile.lock"]
markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Getting Started
   url: /getting-started

social:
   github: natebaldwindesign
   twitter: natebaldwinart
   facebook: 
   email: natebaldwindesign@gmail.com

google_analytics: 
